$('.sort__buttons-list').click(() => {
    $('.products__field-items').addClass('products__field-items--line')
    $('.products__item').addClass('products__item-line')
    $('.products__item-full').addClass('products__item-full--list')
    $('.products__image-field').addClass('products__image-field--line')
    $('.product--link').addClass('product--link--line')
    $('.products__item-name').addClass('products__item-name--line')
    $('.products__bots').addClass('products__bots-line')
    $('.products__item-col--status').addClass('products__item-col--status--line')
    $('.products__item-col--change').addClass('products__item-col--change--line')
    $('.col__price').addClass('col__price-line')
    $('.products__item-price').addClass('products__item-price--line')
})